name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['17', '21', '24']

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
